"""widen profile_picture_url to text for base64 images

Revision ID: 172c1a2eff6b
Revises: 74c0fd328526
Create Date: 2026-06-30 11:45:33.051583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172c1a2eff6b'
down_revision = '74c0fd328526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_picture_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
